-- CreateTable
CREATE TABLE "LatheMachine" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "manufacturer" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "controller" TEXT NOT NULL,
    "machineType" TEXT NOT NULL DEFAULT 'LATHE_2AXIS',
    "axisCount" INTEGER NOT NULL DEFAULT 2,
    "hasCaxis" BOOLEAN NOT NULL DEFAULT false,
    "hasYaxis" BOOLEAN NOT NULL DEFAULT false,
    "hasLiveTooling" BOOLEAN NOT NULL DEFAULT false,
    "hasSubSpindle" BOOLEAN NOT NULL DEFAULT false,
    "hasTailstock" BOOLEAN NOT NULL DEFAULT true,
    "hasBarFeeder" BOOLEAN NOT NULL DEFAULT false,
    "hasPartsCatcher" BOOLEAN NOT NULL DEFAULT false,
    "maxSwing" DOUBLE PRECISION NOT NULL,
    "maxTurningDiameter" DOUBLE PRECISION NOT NULL,
    "maxTurningLength" DOUBLE PRECISION NOT NULL,
    "spindleBore" DOUBLE PRECISION NOT NULL,
    "barCapacity" DOUBLE PRECISION,
    "chuckSize" DOUBLE PRECISION,
    "maxRPM" INTEGER NOT NULL,
    "maxSpindlePower" DOUBLE PRECISION NOT NULL,
    "maxSpindleTorque" DOUBLE PRECISION,
    "xTravel" DOUBLE PRECISION NOT NULL,
    "zTravel" DOUBLE PRECISION NOT NULL,
    "turretStations" INTEGER NOT NULL,
    "coolantTypes" TEXT NOT NULL DEFAULT '[]',
    "throughToolCoolant" BOOLEAN NOT NULL DEFAULT false,
    "probe" BOOLEAN NOT NULL DEFAULT false,
    "toolSetter" BOOLEAN NOT NULL DEFAULT false,
    "supportedPostProcessor" TEXT NOT NULL DEFAULT 'lathe-fanuc-dev',
    "isReferenceProfile" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LatheMachine_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "LatheMachine_organizationId_idx" ON "LatheMachine"("organizationId");

CREATE TABLE "LatheWorkholding" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "manufacturer" TEXT,
    "model" TEXT,
    "description" TEXT NOT NULL,
    "chuckDiameter" DOUBLE PRECISION,
    "maxRPM" INTEGER,
    "maxClampForceLbf" DOUBLE PRECISION,
    "jawType" TEXT,
    "jawStroke" DOUBLE PRECISION,
    "jawMaterial" TEXT,
    "serrated" BOOLEAN,
    "minGripLength" DOUBLE PRECISION,
    "maxGripLength" DOUBLE PRECISION,
    "boreThroughDiameter" DOUBLE PRECISION,
    "colletType" TEXT,
    "colletRange" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LatheWorkholding_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "LatheWorkholding_organizationId_idx" ON "LatheWorkholding"("organizationId");

CREATE TABLE "TurningTool" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "station" TEXT NOT NULL,
    "toolClass" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "insertShape" TEXT,
    "insertGrade" TEXT,
    "noseRadius" DOUBLE PRECISION,
    "leadAngle" DOUBLE PRECISION,
    "handedness" TEXT,
    "barDiameter" DOUBLE PRECISION,
    "minBoreDiameter" DOUBLE PRECISION,
    "maxDepthOfCut" DOUBLE PRECISION,
    "grooveWidth" DOUBLE PRECISION,
    "stickout" DOUBLE PRECISION,
    "overallLength" DOUBLE PRECISION,
    "coolantThrough" BOOLEAN NOT NULL DEFAULT false,
    "surfaceSpeedMin" DOUBLE PRECISION,
    "surfaceSpeedMax" DOUBLE PRECISION,
    "feedPerRevMin" DOUBLE PRECISION,
    "feedPerRevMax" DOUBLE PRECISION,
    "manufacturer" TEXT,
    "productCode" TEXT,
    "condition" TEXT NOT NULL DEFAULT 'UNKNOWN',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TurningTool_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "TurningTool_organizationId_station_key" ON "TurningTool"("organizationId", "station");
CREATE INDEX "TurningTool_organizationId_idx" ON "TurningTool"("organizationId");

CREATE TABLE "RotationalPart" (
    "id" TEXT NOT NULL,
    "partRevisionId" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "profileJson" TEXT NOT NULL,
    "planJson" TEXT NOT NULL DEFAULT '[]',
    "latheMachineId" TEXT,
    "workholdingId" TEXT,
    "gripLength" DOUBLE PRECISION,
    "stickout" DOUBLE PRECISION,
    "clampForceLbf" DOUBLE PRECISION,
    "tailstockActive" BOOLEAN NOT NULL DEFAULT false,
    "maxRpmClamp" INTEGER,
    "humanApproved" BOOLEAN NOT NULL DEFAULT false,
    "approvedById" TEXT,
    "approvedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "RotationalPart_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "RotationalPart_partRevisionId_key" ON "RotationalPart"("partRevisionId");
CREATE INDEX "RotationalPart_organizationId_idx" ON "RotationalPart"("organizationId");
