import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { TopBar } from "@/components/nav";
import { Button, Field, Notice, SectionHeading, inputClass } from "@/components/ui";
import { toolLife } from "@/lib/engines/tool-life";
import { ShopForm } from "@/components/shop-form";
import { toolSections } from "../../tool-fields";
import { updateTool, deleteTool, freshEdge } from "../../actions";

export default async function EditToolPage(props: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ problem?: string }>;
}) {
  const { id } = await props.params;
  const { problem } = await props.searchParams;
  const user = await requireUser();

  // Scoped to the session's organisation. One shop's crib is not reachable
  // from another shop's session, and the id in the URL does not change that.
  const tool = await db.tool.findFirst({ where: { id, organizationId: user.organizationId } });
  if (!tool) notFound();

  const [holders, usedBy] = await Promise.all([
    db.toolHolder.findMany({ orderBy: { taper: "asc" } }),
    db.operation.count({ where: { toolId: id } }),
  ]);

  // What this edge has done, from jobs recorded here. Same verdict the crib
  // list shows, computed from the same engine rather than restated.
  const life = toolLife({
    description: tool.description,
    minutesUsed: tool.minutesUsed,
    partsCut: tool.partsCut,
    expectedLifeMinutes: tool.expectedLifeMinutes,
    lifeCountedFrom: tool.lifeCountedFrom,
    regrindCount: tool.regrindCount,
  });

  return (
    <>
      <TopBar>
        <Link href="/tools" className="tech-label hover:text-platinum">
          Tool crib
        </Link>
        <span className="text-muted">/</span>
        <span className="tech-label">T{tool.toolNumber}</span>
      </TopBar>

      <main className="flex-1 overflow-y-auto p-4 sm:p-6">
        <div className="mx-auto max-w-3xl space-y-6">
          <SectionHeading sub={tool.description}>Edit T{tool.toolNumber}</SectionHeading>

          {problem && (
            <Notice tone="risk" title="Not saved">
              {problem}
            </Notice>
          )}

          {usedBy > 0 && (
            <Notice tone="review" title={`Used by ${usedBy} planned operation${usedBy === 1 ? "" : "s"}`}>
              Changing geometry or cutting data here changes what those operations were planned against. Toolpaths are
              not regenerated by this edit — re-check the affected setups before the next run.
            </Notice>
          )}

          <ShopForm action={updateTool} sections={toolSections(tool, holders)} submitLabel="Save changes" cancelHref="/tools">
            <input type="hidden" name="id" value={tool.id} />
          </ShopForm>

          {/*
            EDGE LIFE.

            Minutes accumulate from jobs marked complete and never fall on
            their own, which is right until somebody regrinds the cutter or
            swaps the inserts. A count that cannot be restarted reads
            PAST_EXPECTED on a brand new edge, and a figure wrong in the
            direction of alarm is ignored exactly as fast as one wrong the
            other way.
          */}
          <div className="border border-line bg-raised px-4 py-3">
            <p className="font-mono text-[11px] uppercase tracking-[0.16em] text-platinum">Edge life</p>
            <p className="mt-1.5 text-[12px] leading-relaxed text-muted">{life.summary}</p>
            <p className="mt-1 text-[11px] leading-relaxed text-muted">{life.caveat}</p>
            <form action={freshEdge} className="mt-3 flex flex-wrap items-end gap-3">
              <input type="hidden" name="id" value={tool.id} />
              <div className="w-44">
                <Field label="Fresh edge" required>
                  <select name="edge" className={inputClass} defaultValue="">
                    <option value="" disabled>
                      Select
                    </option>
                    <option value="NEW_TOOL">New tool</option>
                    <option value="REGRIND">Reground</option>
                    <option value="NEW_INSERTS">New inserts</option>
                  </select>
                </Field>
              </div>
              <div className="min-w-[16rem] flex-1">
                <Field label="Note" hint="Optional. Kept with the count that is being cleared.">
                  <input name="edgeNote" className={inputClass} maxLength={300} />
                </Field>
              </div>
              <Button type="submit" size="sm">
                Restart count
              </Button>
            </form>
          </div>

          <form action={deleteTool} className="border border-line border-l-2 border-l-risk bg-raised px-4 py-3">
            <input type="hidden" name="id" value={tool.id} />
            <p className="font-mono text-[11px] uppercase tracking-[0.16em] text-platinum">Remove from crib</p>
            <p className="mt-1.5 text-[12px] leading-relaxed text-muted">
              {usedBy > 0
                ? `T${tool.toolNumber} is used by ${usedBy} planned operation${usedBy === 1 ? "" : "s"}. It cannot be removed until those operations no longer reference it — deleting it would strip the tooling out of a plan that would still look complete.`
                : "The record is deleted and the removal is logged. Operations planned against it in future revisions will have no tool."}
            </p>
            <div className="mt-2.5">
              <Button type="submit" variant="danger" size="sm" disabled={usedBy > 0}>
                Remove T{tool.toolNumber}
              </Button>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}

export const dynamic = "force-dynamic";
