import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { TopBar } from "@/components/nav";
import { Button, Notice, SectionHeading } from "@/components/ui";
import { ShopForm } from "@/components/shop-form";
import { toolSections } from "../../tool-fields";
import { updateTool, deleteTool } from "../../actions";

export default async function EditToolPage(props: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ problem?: string }>;
}) {
  const { id } = await props.params;
  const { problem } = await props.searchParams;
  const user = await requireUser();

  // Scoped to the session's organisation. One shop's crib is not reachable
  // from another shop's session, and the id in the URL does not change that.
  const tool = await db.tool.findFirst({ where: { id, organizationId: user.organizationId } });
  if (!tool) notFound();

  const [holders, usedBy] = await Promise.all([
    db.toolHolder.findMany({ orderBy: { taper: "asc" } }),
    db.operation.count({ where: { toolId: id } }),
  ]);

  return (
    <>
      <TopBar>
        <Link href="/tools" className="tech-label hover:text-platinum">
          Tool crib
        </Link>
        <span className="text-muted">/</span>
        <span className="tech-label">T{tool.toolNumber}</span>
      </TopBar>

      <main className="flex-1 overflow-y-auto p-4 sm:p-6">
        <div className="mx-auto max-w-3xl space-y-6">
          <SectionHeading sub={tool.description}>Edit T{tool.toolNumber}</SectionHeading>

          {problem && (
            <Notice tone="risk" title="Not saved">
              {problem}
            </Notice>
          )}

          {usedBy > 0 && (
            <Notice tone="review" title={`Used by ${usedBy} planned operation${usedBy === 1 ? "" : "s"}`}>
              Changing geometry or cutting data here changes what those operations were planned against. Toolpaths are
              not regenerated by this edit — re-check the affected setups before the next run.
            </Notice>
          )}

          <ShopForm action={updateTool} sections={toolSections(tool, holders)} submitLabel="Save changes" cancelHref="/tools">
            <input type="hidden" name="id" value={tool.id} />
          </ShopForm>

          <form action={deleteTool} className="border border-line border-l-2 border-l-risk bg-raised px-4 py-3">
            <input type="hidden" name="id" value={tool.id} />
            <p className="font-mono text-[11px] uppercase tracking-[0.16em] text-platinum">Remove from crib</p>
            <p className="mt-1.5 text-[12px] leading-relaxed text-muted">
              {usedBy > 0
                ? `T${tool.toolNumber} is used by ${usedBy} planned operation${usedBy === 1 ? "" : "s"}. It cannot be removed until those operations no longer reference it — deleting it would strip the tooling out of a plan that would still look complete.`
                : "The record is deleted and the removal is logged. Operations planned against it in future revisions will have no tool."}
            </p>
            <div className="mt-2.5">
              <Button type="submit" variant="danger" size="sm" disabled={usedBy > 0}>
                Remove T{tool.toolNumber}
              </Button>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}

export const dynamic = "force-dynamic";
