import { AppError, sha256Hex } from '@masterclip/shared'
import { sanitizeFilename, sanitizeSegment } from '@masterclip/asset-storage'
import { retentionExpiresAt, type RetentionKind } from '@masterclip/audio-core'
import type { AudioAssetRecord, AudioProjectType } from '@masterclip/audio-domain'
import type { Actor, AudioEngineDeps } from './deps.js'

/** Accepted audio/video source types, enforced against sniffed magic bytes. */
export const AUDIO_UPLOAD_TYPES = new Map<string, string>([
  ['audio/wav', 'wav'],
  ['audio/mpeg', 'mp3'],
  ['audio/mp4', 'm4a'],
  ['audio/flac', 'flac'],
  ['audio/ogg', 'ogg'],
  ['video/mp4', 'mp4'],
  ['video/quicktime', 'mov'],
])

export const MAX_AUDIO_UPLOAD_BYTES = 512 * 1024 * 1024

/** Magic-byte sniffing — Content-Type and filename are attacker-controlled. */
export function sniffAudioMime(head: Uint8Array): string | null {
  const bytes = Array.from(head.slice(0, 16))
  const ascii = (from: number, to: number) => String.fromCharCode(...bytes.slice(from, to))
  const startsWith = (...sig: number[]) => sig.every((b, i) => bytes[i] === b)
  if (startsWith(0x52, 0x49, 0x46, 0x46) && ascii(8, 12) === 'WAVE') return 'audio/wav'
  if (startsWith(0x49, 0x44, 0x33) || startsWith(0xff, 0xfb) || startsWith(0xff, 0xf3) || startsWith(0xff, 0xf2)) return 'audio/mpeg'
  if (startsWith(0x66, 0x4c, 0x61, 0x43)) return 'audio/flac'
  if (startsWith(0x4f, 0x67, 0x67, 0x53)) return 'audio/ogg'
  if (ascii(4, 8) === 'ftyp') {
    const brand = ascii(8, 12)
    if (brand.startsWith('qt')) return 'video/quicktime'
    if (brand.startsWith('M4A')) return 'audio/mp4'
    return 'video/mp4'
  }
  return null
}

/**
 * Secure audio storage.
 *
 * Keys are always organizations/{orgId}/audio/{area}/… and built here from
 * sanitised parts — user input can never place bytes outside its tenant
 * prefix. Serving is signed-URL only, upstream of this service.
 */
export class AudioAssetService {
  constructor(private readonly deps: AudioEngineDeps) {}

  storageKey(orgId: string, area: string, assetId: string, filename: string): string {
    return ['organizations', sanitizeSegment(orgId), 'audio', sanitizeSegment(area), sanitizeSegment(assetId), sanitizeFilename(filename)].join('/')
  }

  async storeUpload(input: {
    actor: Actor
    bytes: Uint8Array
    filename: string
    area: string
    projectType: AudioProjectType
    projectId: string | null
    assetType: string
    retentionKind: RetentionKind
    rightsStatus: string
    consentRecordId: string | null
    durationMs?: number | null
  }): Promise<AudioAssetRecord> {
    if (input.bytes.length === 0) {
      throw new AppError({ kind: 'validation', code: 'audio.empty_upload', message: 'the uploaded file is empty' })
    }
    if (input.bytes.length > MAX_AUDIO_UPLOAD_BYTES) {
      throw new AppError({ kind: 'validation', code: 'audio.too_large', message: 'the uploaded file exceeds the 512MB limit' })
    }
    const mime = sniffAudioMime(input.bytes)
    if (!mime || !AUDIO_UPLOAD_TYPES.has(mime)) {
      throw new AppError({
        kind: 'validation',
        code: 'audio.unsupported_type',
        message: 'unsupported file type — upload WAV, MP3, M4A, FLAC, OGG, MP4 or MOV',
      })
    }
    const checksum = sha256Hex(Buffer.from(input.bytes))
    const existing = await this.deps.repos.assets.findByChecksum(input.actor.orgId, checksum)
    if (existing && existing.projectType === input.projectType && existing.projectId === input.projectId) {
      return existing
    }
    const policy = await this.deps.repos.policy.getPolicy(input.actor.orgId)
    const record = await this.deps.repos.assets.create({
      orgId: input.actor.orgId,
      ownerUserId: input.actor.userId,
      projectType: input.projectType,
      projectId: input.projectId,
      assetType: input.assetType,
      storageKey: '',
      fileName: sanitizeFilename(input.filename),
      mimeType: mime,
      fileSize: input.bytes.length,
      durationMs: input.durationMs ?? null,
      checksum,
      rightsStatus: input.rightsStatus,
      consentRecordId: input.consentRecordId,
      retentionKind: input.retentionKind,
      retentionExpiresAt: retentionExpiresAt(policy, input.retentionKind, this.deps.clock.now()),
    })
    const key = this.storageKey(input.actor.orgId, input.area, record.id, record.fileName)
    await this.deps.storage.putBuffer(key, input.bytes, { contentType: mime, sha256: checksum })
    await this.deps.db.run('UPDATE audio_assets SET storage_key = ? WHERE id = ?', [key, record.id])
    return { ...record, storageKey: key }
  }

  /** Stores provider-generated bytes with lineage-friendly metadata. */
  async storeGenerated(input: {
    orgId: string
    ownerUserId: string
    bytes: Uint8Array
    contentType: string
    filename: string
    area: string
    projectType: AudioProjectType
    projectId: string | null
    assetType: string
    retentionKind: RetentionKind
    rightsStatus: string
  }): Promise<AudioAssetRecord> {
    const checksum = sha256Hex(Buffer.from(input.bytes))
    const policy = await this.deps.repos.policy.getPolicy(input.orgId)
    const record = await this.deps.repos.assets.create({
      orgId: input.orgId,
      ownerUserId: input.ownerUserId,
      projectType: input.projectType,
      projectId: input.projectId,
      assetType: input.assetType,
      storageKey: '',
      fileName: sanitizeFilename(input.filename),
      mimeType: input.contentType,
      fileSize: input.bytes.length,
      durationMs: null,
      checksum,
      rightsStatus: input.rightsStatus,
      consentRecordId: null,
      retentionKind: input.retentionKind,
      retentionExpiresAt: retentionExpiresAt(policy, input.retentionKind, this.deps.clock.now()),
    })
    const key = this.storageKey(input.orgId, input.area, record.id, record.fileName)
    await this.deps.storage.putBuffer(key, input.bytes, { contentType: input.contentType, sha256: checksum })
    await this.deps.db.run('UPDATE audio_assets SET storage_key = ? WHERE id = ?', [key, record.id])
    return { ...record, storageKey: key }
  }

  async signedUrl(orgId: string, assetId: string, download = false): Promise<{ url: string; asset: AudioAssetRecord }> {
    const asset = await this.deps.repos.assets.get(orgId, assetId)
    if (download) {
      const policy = await this.deps.repos.policy.getPolicy(orgId)
      if (!policy.allowDownload) {
        throw new AppError({ kind: 'forbidden', code: 'audio.download_disabled', message: 'downloads are disabled by the audio data policy' })
      }
    }
    return { url: await this.deps.storage.signedUrl(asset.storageKey, 3600), asset }
  }

  /** Removes bytes and soft-deletes the row; audit metadata survives. */
  async deleteAsset(orgId: string, assetId: string, reason: string): Promise<void> {
    const asset = await this.deps.repos.assets.markDeleted(orgId, assetId, reason)
    if (asset.storageKey) {
      try {
        await this.deps.storage.delete(asset.storageKey)
      } catch (err) {
        this.deps.logger.warn('audio.asset_delete_bytes_failed', { asset_id: assetId, err })
      }
    }
  }

  async materialize(orgId: string, assetId: string): Promise<{ asset: AudioAssetRecord; bytes: Uint8Array }> {
    const asset = await this.deps.repos.assets.get(orgId, assetId)
    const bytes = await this.deps.storage.getBuffer(asset.storageKey)
    return { asset, bytes }
  }
}
