// Run from inside the app workspace so the package resolves:
//   cd ../masterclip-os && pnpm exec tsx ../demo-video/scripts/score.ts
import { synthesizeWav } from '@masterclip/ai-audio'
import { writeFileSync } from 'node:fs'

/**
 * The film's music bed, generated by the product's own synthesis engine.
 *
 * Using MASTERCLIP's synthesizer means the score is owned outright — no
 * licence question, no third-party stem, and it is literally the product
 * making its own trailer music.
 *
 * Restrained on purpose: a low pad and a soft pulse. The film has to read
 * muted, so the music supports pace and never carries meaning.
 */
const BPM = 96
const BARS = 40 // 40 bars @ 96bpm ≈ 100s, trimmed to the cut

const bed = synthesizeWav({
  bpm: BPM, bars: BARS, energy: 0.34, seed: 20260828,
  layers: { pad: true, bass: true, kick: false, hat: false, riser: false, click: false },
})
writeFileSync('/tmp/score-bed.wav', bed)

// A separate low pulse, mixed far under the pad, to give the cut a floor.
const pulse = synthesizeWav({
  bpm: BPM, bars: BARS, energy: 0.22, seed: 771,
  layers: { pad: false, bass: true, kick: true, hat: false, riser: false, click: false },
})
writeFileSync('/tmp/score-pulse.wav', pulse)

console.log('bed', bed.length, 'pulse', pulse.length)
